### ISSUE TITLE
Data source and update interval?

### ISSUE THREAD

**Issue by tonylukasavage** [tamcap/covid19-vaccine-data#1]
Hi, I was just wondering if it would be possible to update the README with the source of the data and perhaps some details on the intervals with which you plan to update the repo? I'd like to build a trend-based map animation of vaccine distribution and administration by state. If this repo is updated regularly I'd like to use it as my source given a few more details. The CDC source for this data only makes available the latest stats, not the historical trends for each day like this repo.

**Comment by tamcap** [comment]
Hey Tony, I threw in a quick readme. I will try to update the repo every day the original sources provide an update, but they have not exactly always been consistent. Let me know in case of other questions.
